#!/bin/bash
clear
##----- Auto Remove Vmess
data=($(cat /etc/xray/config.json | grep '^###' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
    uuidvm=$(cat /etc/vmess/.vmess.db | grep $user | awk '{print $4}')
    vmip=$(cat /etc/limit/vmess/ip/${user})
    exp=$(grep -w "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(((d1 - d2) / 86400))
    if [[ "$exp2" -le "0" ]]; then
        sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^### $user $exp/d" /etc/vmess/.vmess.db
        sed -i "/^#### $user $exp/d" /etc/vmess/vmess.txt
        sed -i "/^#### $user $exp/d" /etc/vmess/kovm.txt
        echo "#### ${user} ${exp} ${uuidvm} ${vmip}" >>/etc/vmess/recovm.txt
        rm /etc/vmess/${user}
        rm /etc/limit/vmess/${user}
        rm /etc/limit/vmess/ip/${user}
        rm /var/www/html/user/vmess-$user.txt
    fi
done

#----- Auto Remove Vless
data=($(cat /etc/xray/config.json | grep '^#&' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
    uuidvl=$(cat /etc/vless/.vless.db | grep $user | awk '{print $4}')
    vlip=$(cat /etc/limit/vless/ip/${user})
    exp=$(grep -w "^#& $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(((d1 - d2) / 86400))
    if [[ "$exp2" -le "0" ]]; then
        sed -i "/^#& $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^### $user $exp/d" /etc/vless/.vless.db
        sed -i "/^#### $user $exp/d" /etc/vless/vless.txt
        sed -i "/^#### $user $exp/d" /etc/vless/kovl.txt
        echo "#### ${user} ${exp} ${uuidvl} ${vlip}" >>/etc/vless/recovl.txt
        rm /etc/vless/${user}
        rm /etc/limit/vless/${user}
        rm /etc/limit/vless/ip/${user}
        rm /var/www/html/user/vless-$user.txt
    fi
done

#----- Auto Remove Trojan
data=($(cat /etc/xray/config.json | grep '^#!' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
    uuidtr=$(cat /etc/trojan/.trojan.db | grep $user | awk '{print $4}')
    trip=$(cat /etc/limit/trojan/ip/${user})
    exp=$(grep -w "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(((d1 - d2) / 86400))
    if [[ "$exp2" -le "0" ]]; then
        sed -i "/^#! $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^### $user $exp/d" /etc/trojan/.trojan.db
        sed -i "/^#### $user $exp/d" /etc/trojan/trojan.txt
        sed -i "/^#### $user $exp/d" /etc/trojan/kotr.txt
        echo "#### ${user} ${exp} ${uuidtr} ${trip}" >>/etc/trojan/recotr.txt
        rm /etc/trojan/${user}
        rm /etc/limit/trojan/${user}
        rm /etc/limit/trojan/ip/${user}
        rm /var/www/html/user/trojan-$user.txt
    fi
done

#----- Auto Remove SS
data=($(cat /etc/xray/config.json | grep '^###&' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
    uuidss=$(cat /etc/shadowsocks/.shadowsocks.db | grep $user | awk '{print $4}')
    ssip=$(cat /etc/limit/shadowsocks/ip/${user})
    exp=$(grep -w "^###& $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(((d1 - d2) / 86400))
    if [[ "$exp2" -le "0" ]]; then
        sed -i "/^###& $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^### $user $exp/d" /etc/shadowsocks/.shadowsocks.db
        sed -i "/^#### $user $exp/d" /etc/shadowsocks/shadowsocks.txt
        sed -i "/^#### $user $exp/d" /etc/shadowsocks/koss.txt
        echo "#### ${user} ${exp} ${uuidss} ${ssip}" >>/etc/shadowsocks/recoss.txt
        rm /etc/shadowsocks/${user}
        rm /etc/limit/shadowsocks/${user}
        rm /etc/limit/shadowsocks/ip/${user}
        rm /var/www/html/user/ss-$user.txt
    fi
done
systemctl restart xray

##------ Auto Remove SSH
hariini=`date +%d-%m-%Y`
cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
totalaccounts=`cat /tmp/expirelist.txt | wc -l`
for((i=1; i<=$totalaccounts; i++ ))
do
  tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
  username=`echo $tuserval | cut -f1 -d:`
  userexp=`echo $tuserval | cut -f2 -d:`
  userexpireinseconds=$(( $userexp * 86400 ))
  exp10=$(grep -wE "^### $username" "/etc/sshku/.sshku.db" | cut -d ' ' -f 3 | sort | uniq)
  tglexp=`date -d @$userexpireinseconds`             
  tgl=`echo $tglexp |awk -F" " '{print $3}'`
  while [ ${#tgl} -lt 2 ]
  do
    tgl="0"$tgl
  done
  while [ ${#username} -lt 15 ]
  do
    username=$username" " 
  done
  bulantahun=`echo $tglexp |awk -F" " '{print $2,$6}'`
  todaystime=`date +%s`
  if [ $userexpireinseconds -ge $todaystime ] ;
  then
    :
  else
    sed -i "/^### $username $exp10/d" /etc/sshku/.sshku.db
    rm /var/www/html/user/ssh-$username.txt    
    userdel --force $username
  fi
done
systemctl reload ssh
systemctl restart udp-custom
systemctl restart tunws@sochs
